# Regressão com MLPs

As MLPs também podem ser usadas para tarefas de regressão. Se quiser predizer um valor único (por exemplo, o preço de um imóvel, levando em conta muitas de suas características), precisará somente de um único neurônio de saída: sua saída é o valor predito. Para regressão multivariada (ou seja, para predizer diversos valores de uma vez), você precisa de um neurônio de saída por dimensão de saída. 

Em geral, ao criar uma MLP para regressão, você não quer usar nenhuma função de ativação para os neurônios de saída; portanto, eles ficam livres para gerar a saída de qualquer intervalo de valores. Caso deseje garantir que a saída seja sempre positiva, poderá usar a função de ativação ReLU na camada de saída. Como alternativa, você pode utilizar a função de ativação *softplus*, uma variante suave da função ReLU:

> softplus(z) = log(1 + exp(z))

Ela fica próxima de 0 quando z é negativo e fica próxima de z quando z é positivo. Por fim, se você quiser garantir que as predições fiquem dentro de um determinado intervalo de valores, poderá empregar a função logística ou a tangente hiperbólica e escalonar os rótulos para o intervalo apropriado: 0 a 1 para a função logística e de -1 a 1 para a tangente hiperbólica.

A função de perda a ser usada durante o treinamento é normalmente o erro médio quadrático, mas, se tiver muitos outliers no conjunto de treinamento, poderá preferir utilizar o erro absoluto médio. Como alternativa, você pode usar a função perda de huber, uma combinação de ambas. 

> A perda de Huber é quadrática quando o erro é menor que um limiar L (normalmente 1), e linear quando o erro é maior que L. A parte linear a deixa menos sensível aos outliers do que o erro médio quadrático e a parte quadrática possibilita convergir mais rapidamente e ter mais precisão que o erro médio absoluto.

<p align=center>
<img src="https://github.com/vitorbeltrao/Pictures/blob/main/arq_tipica_mlp_regressao.png?raw=true" width="50%"></p>

In [1]:
# importar os pacotes necessários
import os
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import RandomizedSearchCV
from scikeras.wrappers import KerasRegressor
from datasets import load_dataset
from scipy.stats import reciprocal


import warnings
warnings.filterwarnings('ignore')

/Users/vitorabdo/Desktop/personal_work/dl_book/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# carregar o conjunto de dados
HUGGINGFACE_API_KEY = os.environ.get("HUGGINGFACE_API_KEY")
dataset = load_dataset(
    "penikmatrumput/nasa-cmapss-rul",
    token=HUGGINGFACE_API_KEY
)

In [3]:
# ler os dados de treino e teste como um dataframe pandas
df_train = pd.DataFrame(dataset["train"])
df_test = pd.DataFrame(dataset["test"])

# verificar o tamanho dos dados de treino e teste
print("Tamanho do conjunto de dados de treino:", len(df_train))
print("Tamanho do conjunto de dados de teste:", len(df_test))

Tamanho do conjunto de dados de treino: 160359
Tamanho do conjunto de dados de teste: 104897

In [4]:
# visualizar as primeiras linhas do conjunto de dados de treino
df_train.head()

,unit_number,time_in_cycles,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,191
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,190
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,189
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,188
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,187

## Pré-processamento dos dados

In [5]:
# criar um pipeline de pré-processamento para os dados
pipeline = Pipeline([
    ("scaling", StandardScaler())
])

In [6]:
# transformando os dados de treino, validação e teste
X_train = pipeline.fit_transform(df_train.drop(columns=["RUL"]))
y_train = df_train["RUL"].values

X_test = pipeline.transform(df_test.drop(columns=["RUL"]))
y_test = df_test["RUL"].values

In [8]:
# visualizar uma amostra dos dados transformados
feature_names = pipeline.named_steps["scaling"].get_feature_names_out()

df = pd.DataFrame(
    X_train,
    columns=feature_names
)

df.head()

,unit_number,time_in_cycles,op_setting_1,op_setting_2,op_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,-1.434856,-1.464382,-1.041429,-1.115418,0.345955,1.079185,1.046626,1.037990,1.024534,1.107714,...,1.113752,0.345200,0.616065,-0.845217,0.963589,1.009022,0.801655,0.345955,1.121962,1.119494
1,-1.434856,-1.452411,-1.041272,-1.115146,0.345955,1.079185,1.054395,1.055929,1.043169,1.107714,...,1.117528,0.345649,0.527629,-0.828851,0.963589,1.009022,0.801655,0.345955,1.116830,1.120150
2,-1.434856,-1.440440,-1.041647,-1.113516,0.345955,1.079185,1.059103,1.023520,1.050946,1.107714,...,1.118380,0.345289,0.549211,-0.847479,0.963589,0.944550,0.801655,0.345955,1.112553,1.108831
3,-1.434856,-1.428470,-1.041344,-1.114331,0.345955,1.079185,1.059103,0.979517,1.033851,1.107714,...,1.121060,0.345739,0.556653,-0.913473,0.963589,1.009022,0.801655,0.345955,1.106566,1.113065
4,-1.434856,-1.416499,-1.041502,-1.114874,0.345955,1.079185,1.059574,0.980025,1.065766,1.107714,...,1.116979,0.345379,0.556281,-0.832044,0.963589,1.041258,0.801655,0.345955,1.108277,1.117413

## Modelagem

Usar a sequential API para criar, treinar, avaliar e usar uma MLP de regressão com o intuito de fazer predições é muito semelhante ao que fizemos para a classificação.

As principais diferenças são o fato de a camada de saída ter um único neurônio (visto que queremos predizer somente um único valor) e não usar nenhuma função de ativação; a função de perda é o erro qudrático médio (MSE).

In [9]:
model = keras.models.Sequential([
    # define o formato de entrada que a rede espera receber
    keras.layers.Input(shape=(X_train.shape[1],)),
    
    # camadas densas (totalmente conectadas)
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(64, activation="relu"),

    # camada de saída sem função de ativação
    keras.layers.Dense(1)
])

In [10]:
# exibir todas as camadas do modelo
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         3,456 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,777 (46.00 KB)

 Trainable params: 11,777 (46.00 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
# compilação do modelo
model.compile(
    optimizer="sgd",
    loss="huber",
    metrics=["mean_absolute_error"]
)

In [12]:
# treinando e avaliando o modelo
history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=32,
    shuffle=True
)

Epoch 1/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 222us/step - loss: 47.3964 - mean_absolute_error: 47.8934 - val_loss: 42.2531 - val_mean_absolute_error: 42.7503
Epoch 2/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 211us/step - loss: 35.1477 - mean_absolute_error: 35.6435 - val_loss: 41.5479 - val_mean_absolute_error: 42.0451
Epoch 3/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 206us/step - loss: 33.5326 - mean_absolute_error: 34.0278 - val_loss: 41.2224 - val_mean_absolute_error: 41.7185
Epoch 4/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 205us/step - loss: 32.9612 - mean_absolute_error: 33.4563 - val_loss: 39.4294 - val_mean_absolute_error: 39.9257
Epoch 5/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step - loss: 32.5034 - mean_absolute_error: 32.9985 - val_loss: 41.0225 - val_mean_absolute_error: 41.5185
Epoch 6/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 203us/step - loss: 32.1846 - mean_absolute_error: 32.6793 - val_loss: 39.5117 - val_mean_absolute_error: 40.0074
Epoch 7/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 200us/step - loss: 31.9981 - mean_absolute_error: 32.4928 - val_loss: 40.2157 - val_mean_absolute_error: 40.7110
Epoch 8/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 206us/step - loss: 31.5738 - mean_absolute_error: 32.0681 - val_loss: 38.5597 - val_mean_absolute_error: 39.0555
Epoch 9/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 31.4327 - mean_absolute_error: 31.9271 - val_loss: 39.5299 - val_mean_absolute_error: 40.0253
Epoch 10/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 31.4939 - mean_absolute_error: 31.9881 - val_loss: 39.8143 - val_mean_absolute_error: 40.3105
Epoch 11/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 31.3017 - mean_absolute_error: 31.7959 - val_loss: 39.4450 - val_mean_absolute_error: 39.9410
Epoch 12/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 200us/step - loss: 30.9980 - mean_absolute_error: 31.4923 - val_loss: 38.8785 - val_mean_absolute_error: 39.3738
Epoch 13/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 30.9931 - mean_absolute_error: 31.4871 - val_loss: 38.9355 - val_mean_absolute_error: 39.4312
Epoch 14/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 200us/step - loss: 30.8963 - mean_absolute_error: 31.3904 - val_loss: 38.8633 - val_mean_absolute_error: 39.3597
Epoch 15/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 200us/step - loss: 30.8450 - mean_absolute_error: 31.3392 - val_loss: 41.7113 - val_mean_absolute_error: 42.2060
Epoch 16/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 200us/step - loss: 30.6776 - mean_absolute_error: 31.1718 - val_loss: 37.8512 - val_mean_absolute_error: 38.3461
Epoch 17/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 30.7719 - mean_absolute_error: 31.2660 - val_loss: 39.5796 - val_mean_absolute_error: 40.0744
Epoch 18/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 30.6978 - mean_absolute_error: 31.1917 - val_loss: 39.2581 - val_mean_absolute_error: 39.7527
Epoch 19/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 30.2967 - mean_absolute_error: 30.7908 - val_loss: 38.7416 - val_mean_absolute_error: 39.2365
Epoch 20/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 30.4762 - mean_absolute_error: 30.9703 - val_loss: 37.8646 - val_mean_absolute_error: 38.3597
Epoch 21/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 30.3292 - mean_absolute_error: 30.8231 - val_loss: 39.8042 - val_mean_absolute_error: 40.2995
Epoch 22/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 211us/step - loss: 30.3656 - mean_absolute_error: 30.8594 - val_loss: 39.4482 - val_mean_absolute_error: 39.9436
Epoch 23/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 222us/step - loss: 30.1224 - mean_absolute_error: 30.6166 - val_loss: 39.7552 - val_mean_absolute_error: 40.2510
Epoch 24/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 30.2060 - mean_absolute_error: 30.7000 - val_loss: 38.8641 - val_mean_absolute_error: 39.3602
Epoch 25/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 30.1329 - mean_absolute_error: 30.6269 - val_loss: 39.6846 - val_mean_absolute_error: 40.1799
Epoch 26/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 30.0021 - mean_absolute_error: 30.4959 - val_loss: 39.8958 - val_mean_absolute_error: 40.3914
Epoch 27/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.9089 - mean_absolute_error: 30.4023 - val_loss: 40.4099 - val_mean_absolute_error: 40.9056
Epoch 28/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.8918 - mean_absolute_error: 30.3857 - val_loss: 38.6439 - val_mean_absolute_error: 39.1393
Epoch 29/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 29.8897 - mean_absolute_error: 30.3837 - val_loss: 39.4415 - val_mean_absolute_error: 39.9372
Epoch 30/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 201us/step - loss: 29.8040 - mean_absolute_error: 30.2978 - val_loss: 39.2852 - val_mean_absolute_error: 39.7810

O treinamento desse modelo pode durar por horas. Isso é bastante comum, principalmente quando treinamos grandes conjuntos de dados. Nesse caso, você não deve salvar seu modelo apenas no fim do treinamento, como também salvar pontos de verificação em intervalos regulares durante o treinamento, para evitar que tudo se perca, caso a sua máquina trave.

**Usando as funções de callbacks**

O método *fit()* aceita um argumento *callbacks* que permite especificar uma lista de objetos que a Keras chamará no início e no fim do treinamento, no início e no fim de cada época, e antes e depois do processamento de cada batch. Por exemplo, o callback *ModelCheckpoint* salva os pontos de verificação do modelo em intervalos regulares durante o treinamento, por padrão no fim de cada época.

In [13]:
# usando as funções de callbacks: modelcheckpoint
checkpoint_cb = keras.callbacks.ModelCheckpoint(
    "saved_models/best_regression_model.keras", save_best_only=True
)
# history = model.fit(
#     X_train, y_train,
#     validation_split=0.2,
#     epochs=30,
#     batch_size=32,
#     shuffle=True,
#     callbacks=[checkpoint_cb]
# )

Nesse caso acima, como estamos utilizando um conjunto de validação durante o treinamento, podemos definir *save_best_only=True* ao criar o check point. Dessa forma, ele apenas salvará seu modelo quando o desempenho no conjunto de validação até então for o melhor. Desse modo, você não precisa se preocupar muito com o treinamento e com um possível overfitting: basta restaurar o último modelo salvo após o treinamento e este será o melhor modelo no conjunto de validação.

Outra callback que podemos utilizar é a *EarlyStopping*. Ela interromperá o treinamento quando não calcular nenhum progresso na validação definida para várias épocas (definida pelo argumento *patience*) e, opcionalmente, reverterá para o melhor modelo. Você pode combinar as duas callbacks para salvar os pontos de verificação do modelo e interromper o treinamento com antecedência, quando não houver mais progresso (a fim de evitar perda de tempo e recursos).

In [14]:
# usando as funções de callbacks: modelcheckpoint e earlystopping
early_stopping_cb = keras.callbacks.EarlyStopping(
    patience=10, 
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    shuffle=True,
    callbacks=[checkpoint_cb, early_stopping_cb]
)

Epoch 1/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step - loss: 29.8482 - mean_absolute_error: 30.3423 - val_loss: 38.4106 - val_mean_absolute_error: 38.9064
Epoch 2/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 204us/step - loss: 29.8045 - mean_absolute_error: 30.2985 - val_loss: 38.8790 - val_mean_absolute_error: 39.3746
Epoch 3/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step - loss: 29.8522 - mean_absolute_error: 30.3457 - val_loss: 38.6530 - val_mean_absolute_error: 39.1494
Epoch 4/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 207us/step - loss: 29.7619 - mean_absolute_error: 30.2558 - val_loss: 40.2757 - val_mean_absolute_error: 40.7716
Epoch 5/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.8007 - mean_absolute_error: 30.2946 - val_loss: 39.3862 - val_mean_absolute_error: 39.8816
Epoch 6/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.6534 - mean_absolute_error: 30.1471 - val_loss: 40.2001 - val_mean_absolute_error: 40.6957
Epoch 7/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 203us/step - loss: 29.6211 - mean_absolute_error: 30.1147 - val_loss: 39.0217 - val_mean_absolute_error: 39.5173
Epoch 8/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.5231 - mean_absolute_error: 30.0169 - val_loss: 39.6431 - val_mean_absolute_error: 40.1388
Epoch 9/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step - loss: 29.3860 - mean_absolute_error: 29.8798 - val_loss: 39.5698 - val_mean_absolute_error: 40.0652
Epoch 10/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step - loss: 29.4337 - mean_absolute_error: 29.9272 - val_loss: 39.2591 - val_mean_absolute_error: 39.7550
Epoch 11/100
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 215us/step - loss: 29.3190 - mean_absolute_error: 29.8125 - val_loss: 39.9030 - val_mean_absolute_error: 40.3984

O número de épocas até pode ser definido como um valor alto, uma vez que o treinamento será interrompido automaticamente quando não progredir mais. Nesse caso, não há necessidade de restaurar o melhor modelo salvo, pois a callback da *EarlyStopping* vai rastrear os melhores pesos e os restaurar no fim do treinamento.

Se precisar de controle extra, você pode escrever as suas próprias callbacks.

**Aperfeiçoando os hiperparâmetros das redes neurais**

A flexibilidade das redes neurais também é um de seus principais empecilhos: existem muitos hiperparâmetros para ajustar. Você pode alterar o número de camadas, o número de neurônios por camada, o tipo de função de ativação a ser usada em cada camada, a lógica de inicialização de peso e muito mais. Mas como saber qual a combinação de hiperparâmetros é a melhor para sua tarefa?

Uma opção é simplesmente testar uma diversidade de combinações de hiperparâmetros e ver qual funciona melhor no conjunto de validação (ou usar a validação cruzada). Por exemplo, podemos utilizar o *GridSearchCV* ou o *RandomizedSearchCV* para explorar o espaço dos hiperparâmetros. Para tal, é necessário empacotarmos nossos modelos Keras em objetos que imitem os regressores regulares da Scikit-Learn. O primeiro passo é criar uma função que construirá e compilará um modelo Keras, levando em conta um conjunto de hiperparâmetros.

In [15]:
# função que compila modelo keras levando em conta um conjunto de hiperparametros
def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=10):
    model = keras.models.Sequential()
    model.add(keras.layers.Input(shape=(input_shape,)))

    # camadas densas (totalmente conectadas)
    for layer in range(n_hidden):
        model.add(
            keras.layers.Dense(
                n_neurons,
                activation="relu"
            )
        )

    # camada de saída sem função de ativação
    model.add(keras.layers.Dense(1))

    model.compile(
        optimizer=keras.optimizers.SGD(
            learning_rate=learning_rate
        ),
        loss="huber",
        metrics=["mean_absolute_error"]
    )

    return model

Essa função cria um modelo *Sequential* simples para regressão univariada (e somente um neurônio de saída), com o formato de entrada fornecido e o número especificado de camadas e neurônios ocultos, e os compila usando um otimizador *SGD* definido com a taxa de aprendizado especificada. É uma boa prática fornecer padrões razoáveis para tantos hiperparâmetros quanto possível, como a Scikit-Learn faz.

Agora, criaremos um *KerasRegressor* com base na função *build_model()*.

In [16]:
# criar um wrapper em torno do modelo keras
keras_reg = KerasRegressor(
    model=build_model,
    model__n_hidden=1,
    model__n_neurons=30,
    model__learning_rate=3e-3,
    model__input_shape=X_train.shape[1]
)

O objeto *KerasRegressor* é um pequeno wrapper em torno do modelo Keras criado e que usa o *build_model()*. Como não especificamos nenhum hiperparâmetro ao criá-lo, ele usará os hiperparâmetros padrão que definimos no *build_model()*. Agora, podemos usar esse objeto como um regressor da Scikit-Learn comum: podemos treiná-lo usando seu método *fit()*, depois avaliá-lo utilizando o método *score()* e usá-lo para fazer previsões por meio do método *predict()*.

In [17]:
# treinar e avaliar o modelo
history = keras_reg.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=32,
    shuffle=True,
    callbacks=[checkpoint_cb, early_stopping_cb]
)

mse_test = keras_reg.score(X_test, y_test)
print("MSE no conjunto de teste:", mse_test)

y_pred = keras_reg.predict(X_test)
plt.scatter(y_test, y_pred)
plt.xlabel("Valores Reais")
plt.ylabel("Valores Preditos")
plt.title("Valores Reais vs. Valores Preditos")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.show()

Epoch 1/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 184us/step - loss: 72.9976 - mean_absolute_error: 73.4957 - val_loss: 57.0694 - val_mean_absolute_error: 57.5670
Epoch 2/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 168us/step - loss: 42.8358 - mean_absolute_error: 43.3328 - val_loss: 53.4326 - val_mean_absolute_error: 53.9302
Epoch 3/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 173us/step - loss: 40.4312 - mean_absolute_error: 40.9281 - val_loss: 49.9431 - val_mean_absolute_error: 50.4402
Epoch 4/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 170us/step - loss: 38.0288 - mean_absolute_error: 38.5249 - val_loss: 45.7943 - val_mean_absolute_error: 46.2917
Epoch 5/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 172us/step - loss: 36.1330 - mean_absolute_error: 36.6287 - val_loss: 43.4200 - val_mean_absolute_error: 43.9172
Epoch 6/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 34.6300 - mean_absolute_error: 35.1256 - val_loss: 42.9016 - val_mean_absolute_error: 43.3988
Epoch 7/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 34.1420 - mean_absolute_error: 34.6375 - val_loss: 41.7922 - val_mean_absolute_error: 42.2890
Epoch 8/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 33.5647 - mean_absolute_error: 34.0601 - val_loss: 41.7278 - val_mean_absolute_error: 42.2245
Epoch 9/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 33.2308 - mean_absolute_error: 33.7262 - val_loss: 40.5085 - val_mean_absolute_error: 41.0054
Epoch 10/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 171us/step - loss: 32.9072 - mean_absolute_error: 33.4025 - val_loss: 39.8293 - val_mean_absolute_error: 40.3257
Epoch 11/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 32.7957 - mean_absolute_error: 33.2908 - val_loss: 39.3676 - val_mean_absolute_error: 39.8640
Epoch 12/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 32.4313 - mean_absolute_error: 32.9266 - val_loss: 39.1119 - val_mean_absolute_error: 39.6086
Epoch 13/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 169us/step - loss: 32.4079 - mean_absolute_error: 32.9028 - val_loss: 38.9158 - val_mean_absolute_error: 39.4124
Epoch 14/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 169us/step - loss: 32.3776 - mean_absolute_error: 32.8723 - val_loss: 39.2895 - val_mean_absolute_error: 39.7859
Epoch 15/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 170us/step - loss: 32.0063 - mean_absolute_error: 32.5011 - val_loss: 38.5873 - val_mean_absolute_error: 39.0836
Epoch 16/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 32.2108 - mean_absolute_error: 32.7057 - val_loss: 38.8351 - val_mean_absolute_error: 39.3311
Epoch 17/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 32.0119 - mean_absolute_error: 32.5065 - val_loss: 38.8499 - val_mean_absolute_error: 39.3459
Epoch 18/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 32.0548 - mean_absolute_error: 32.5494 - val_loss: 38.6960 - val_mean_absolute_error: 39.1920
Epoch 19/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 32.1151 - mean_absolute_error: 32.6098 - val_loss: 38.6776 - val_mean_absolute_error: 39.1733
Epoch 20/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 31.8783 - mean_absolute_error: 32.3729 - val_loss: 38.2943 - val_mean_absolute_error: 38.7902
Epoch 21/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 168us/step - loss: 31.9768 - mean_absolute_error: 32.4716 - val_loss: 38.4203 - val_mean_absolute_error: 38.9158
Epoch 22/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 31.7445 - mean_absolute_error: 32.2391 - val_loss: 38.4613 - val_mean_absolute_error: 38.9573
Epoch 23/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 165us/step - loss: 31.8400 - mean_absolute_error: 32.3344 - val_loss: 38.7652 - val_mean_absolute_error: 39.2607
Epoch 24/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 31.7245 - mean_absolute_error: 32.2189 - val_loss: 38.9375 - val_mean_absolute_error: 39.4329
Epoch 25/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 167us/step - loss: 31.8751 - mean_absolute_error: 32.3696 - val_loss: 38.2979 - val_mean_absolute_error: 38.7938
Epoch 26/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 165us/step - loss: 31.6748 - mean_absolute_error: 32.1695 - val_loss: 38.1365 - val_mean_absolute_error: 38.6324
Epoch 27/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 171us/step - loss: 31.6203 - mean_absolute_error: 32.1147 - val_loss: 38.2382 - val_mean_absolute_error: 38.7339
Epoch 28/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 170us/step - loss: 31.7939 - mean_absolute_error: 32.2884 - val_loss: 38.0416 - val_mean_absolute_error: 38.5374
Epoch 29/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 165us/step - loss: 31.6106 - mean_absolute_error: 32.1053 - val_loss: 38.2169 - val_mean_absolute_error: 38.7121
Epoch 30/30
4009/4009 ━━━━━━━━━━━━━━━━━━━━ 1s 166us/step - loss: 31.5950 - mean_absolute_error: 32.0894 - val_loss: 38.1931 - val_mean_absolute_error: 38.6886

ValueError: Input contains NaN.

Qualquer parâmetro extra que passar para o método *fit()* será passado para o modelo Keras subjacente. Repare também que o score será o oposto do MSE, pois a Scikit-Learn quer scores e não perdas (ou seja, os maiores devem ser melhores). Não queremos treinar um único modelo como este, queremos treinar centenas de variantes e ver qual delas apresenta o melhor desempenho no conjunto de validação. Já que existem muitos hiperparâmetros, é preferível usar um randomized search em vez do grid search.

In [ ]:
# treinar e avaliar o modelo usando o randomized search
param_distribs = {
    "model__n_hidden": [0, 1, 2, 3],
    "model__n_neurons": np.arange(1, 100),
    "model__learning_rate": reciprocal(3e-4, 3e-2)
}

rnd_search_cv = RandomizedSearchCV(
    keras_reg,
    param_distribs,
    n_iter=5,
    cv=3
)

rnd_search_cv.fit(
    X_train, y_train, 
    epochs=100, 
    validation_split=0.2,
    callbacks=[checkpoint_cb, early_stopping_cb]
)

Epoch 1/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 1s 178us/step - loss: 126.1348 - mean_absolute_error: 126.6336 - val_loss: 129.1414 - val_mean_absolute_error: 129.6401
Epoch 2/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 122.1586 - mean_absolute_error: 122.6572 - val_loss: 125.4556 - val_mean_absolute_error: 125.9543
Epoch 3/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 118.1444 - mean_absolute_error: 118.6430 - val_loss: 121.9748 - val_mean_absolute_error: 122.4733
Epoch 4/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 114.2093 - mean_absolute_error: 114.7076 - val_loss: 118.6563 - val_mean_absolute_error: 119.1549
Epoch 5/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 111.3096 - mean_absolute_error: 111.8083 - val_loss: 115.4940 - val_mean_absolute_error: 115.9927
Epoch 6/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 161us/step - loss: 107.6315 - mean_absolute_error: 108.1300 - val_loss: 112.4595 - val_mean_absolute_error: 112.9581
Epoch 7/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 167us/step - loss: 104.2197 - mean_absolute_error: 104.7182 - val_loss: 109.6479 - val_mean_absolute_error: 110.1466
Epoch 8/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 161us/step - loss: 101.6048 - mean_absolute_error: 102.1033 - val_loss: 106.9472 - val_mean_absolute_error: 107.4457
Epoch 9/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 98.2994 - mean_absolute_error: 98.7979 - val_loss: 104.3428 - val_mean_absolute_error: 104.8416
Epoch 10/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 161us/step - loss: 95.5144 - mean_absolute_error: 96.0129 - val_loss: 101.8620 - val_mean_absolute_error: 102.3604
Epoch 11/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 93.3622 - mean_absolute_error: 93.8606 - val_loss: 99.5022 - val_mean_absolute_error: 100.0007
Epoch 12/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 90.9964 - mean_absolute_error: 91.4949 - val_loss: 97.2138 - val_mean_absolute_error: 97.7122
Epoch 13/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 88.3498 - mean_absolute_error: 88.8480 - val_loss: 95.0653 - val_mean_absolute_error: 95.5638
Epoch 14/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 85.7570 - mean_absolute_error: 86.2552 - val_loss: 92.9838 - val_mean_absolute_error: 93.4821
Epoch 15/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 172us/step - loss: 83.5569 - mean_absolute_error: 84.0552 - val_loss: 91.0410 - val_mean_absolute_error: 91.5395
Epoch 16/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 82.1689 - mean_absolute_error: 82.6670 - val_loss: 89.1407 - val_mean_absolute_error: 89.6391
Epoch 17/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 79.7737 - mean_absolute_error: 80.2720 - val_loss: 87.3325 - val_mean_absolute_error: 87.8309
Epoch 18/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 77.8187 - mean_absolute_error: 78.3171 - val_loss: 85.6456 - val_mean_absolute_error: 86.1440
Epoch 19/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 75.8028 - mean_absolute_error: 76.3011 - val_loss: 84.0256 - val_mean_absolute_error: 84.5240
Epoch 20/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 74.1522 - mean_absolute_error: 74.6505 - val_loss: 82.4632 - val_mean_absolute_error: 82.9614
Epoch 21/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 72.4118 - mean_absolute_error: 72.9098 - val_loss: 80.9800 - val_mean_absolute_error: 81.4783
Epoch 22/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 70.7646 - mean_absolute_error: 71.2628 - val_loss: 79.5811 - val_mean_absolute_error: 80.0793
Epoch 23/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 69.4017 - mean_absolute_error: 69.8998 - val_loss: 78.2719 - val_mean_absolute_error: 78.7698
Epoch 24/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 67.9614 - mean_absolute_error: 68.4597 - val_loss: 77.0015 - val_mean_absolute_error: 77.4996
Epoch 25/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 66.7543 - mean_absolute_error: 67.2523 - val_loss: 75.8312 - val_mean_absolute_error: 76.3295
Epoch 26/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 65.3753 - mean_absolute_error: 65.8734 - val_loss: 74.7577 - val_mean_absolute_error: 75.2560
Epoch 27/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 64.5435 - mean_absolute_error: 65.0415 - val_loss: 73.7204 - val_mean_absolute_error: 74.2187
Epoch 28/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 62.4025 - mean_absolute_error: 62.9004 - val_loss: 72.7803 - val_mean_absolute_error: 73.2785
Epoch 29/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 62.7006 - mean_absolute_error: 63.1984 - val_loss: 71.8289 - val_mean_absolute_error: 72.3271
Epoch 30/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 60.9634 - mean_absolute_error: 61.4613 - val_loss: 70.9954 - val_mean_absolute_error: 71.4935
Epoch 31/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 60.5081 - mean_absolute_error: 61.0062 - val_loss: 70.2031 - val_mean_absolute_error: 70.7014
Epoch 32/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 59.6182 - mean_absolute_error: 60.1161 - val_loss: 69.4455 - val_mean_absolute_error: 69.9437
Epoch 33/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 58.5990 - mean_absolute_error: 59.0967 - val_loss: 68.7722 - val_mean_absolute_error: 69.2703
Epoch 34/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 57.9314 - mean_absolute_error: 58.4290 - val_loss: 68.1463 - val_mean_absolute_error: 68.6444
Epoch 35/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 170us/step - loss: 57.2532 - mean_absolute_error: 57.7511 - val_loss: 67.6008 - val_mean_absolute_error: 68.0988
Epoch 36/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 56.6305 - mean_absolute_error: 57.1283 - val_loss: 67.0595 - val_mean_absolute_error: 67.5576
Epoch 37/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 56.4642 - mean_absolute_error: 56.9620 - val_loss: 66.6009 - val_mean_absolute_error: 67.0987
Epoch 38/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 56.2138 - mean_absolute_error: 56.7113 - val_loss: 66.1676 - val_mean_absolute_error: 66.6657
Epoch 39/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 55.8200 - mean_absolute_error: 56.3177 - val_loss: 65.7495 - val_mean_absolute_error: 66.2474
Epoch 40/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 168us/step - loss: 54.9638 - mean_absolute_error: 55.4613 - val_loss: 65.3970 - val_mean_absolute_error: 65.8949
Epoch 41/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 54.8503 - mean_absolute_error: 55.3480 - val_loss: 65.0515 - val_mean_absolute_error: 65.5494
Epoch 42/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 54.8960 - mean_absolute_error: 55.3939 - val_loss: 64.7401 - val_mean_absolute_error: 65.2383
Epoch 43/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 54.2079 - mean_absolute_error: 54.7057 - val_loss: 64.4610 - val_mean_absolute_error: 64.9592
Epoch 44/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 53.6488 - mean_absolute_error: 54.1465 - val_loss: 64.2202 - val_mean_absolute_error: 64.7184
Epoch 45/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 53.7065 - mean_absolute_error: 54.2041 - val_loss: 63.9955 - val_mean_absolute_error: 64.4936
Epoch 46/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 53.4170 - mean_absolute_error: 53.9145 - val_loss: 63.7839 - val_mean_absolute_error: 64.2820
Epoch 47/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 53.5589 - mean_absolute_error: 54.0564 - val_loss: 63.5770 - val_mean_absolute_error: 64.0752
Epoch 48/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 53.1974 - mean_absolute_error: 53.6949 - val_loss: 63.3991 - val_mean_absolute_error: 63.8971
Epoch 49/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 53.1131 - mean_absolute_error: 53.6108 - val_loss: 63.2116 - val_mean_absolute_error: 63.7096
Epoch 50/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 169us/step - loss: 53.4031 - mean_absolute_error: 53.9006 - val_loss: 63.0693 - val_mean_absolute_error: 63.5671
Epoch 51/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.9080 - mean_absolute_error: 53.4057 - val_loss: 62.9390 - val_mean_absolute_error: 63.4368
Epoch 52/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 175us/step - loss: 52.9371 - mean_absolute_error: 53.4349 - val_loss: 62.7875 - val_mean_absolute_error: 63.2854
Epoch 53/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 52.4565 - mean_absolute_error: 52.9544 - val_loss: 62.6844 - val_mean_absolute_error: 63.1823
Epoch 54/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 168us/step - loss: 52.7457 - mean_absolute_error: 53.2435 - val_loss: 62.5780 - val_mean_absolute_error: 63.0759
Epoch 55/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.5820 - mean_absolute_error: 53.0796 - val_loss: 62.4686 - val_mean_absolute_error: 62.9664
Epoch 56/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 52.5562 - mean_absolute_error: 53.0540 - val_loss: 62.3555 - val_mean_absolute_error: 62.8533
Epoch 57/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 52.2410 - mean_absolute_error: 52.7387 - val_loss: 62.2467 - val_mean_absolute_error: 62.7443
Epoch 58/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 52.2893 - mean_absolute_error: 52.7871 - val_loss: 62.1651 - val_mean_absolute_error: 62.6627
Epoch 59/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.2926 - mean_absolute_error: 52.7901 - val_loss: 62.0799 - val_mean_absolute_error: 62.5776
Epoch 60/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 52.4510 - mean_absolute_error: 52.9486 - val_loss: 62.0132 - val_mean_absolute_error: 62.5110
Epoch 61/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.6504 - mean_absolute_error: 53.1483 - val_loss: 61.9204 - val_mean_absolute_error: 62.4184
Epoch 62/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 52.0328 - mean_absolute_error: 52.5305 - val_loss: 61.8700 - val_mean_absolute_error: 62.3682
Epoch 63/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.3353 - mean_absolute_error: 52.8331 - val_loss: 61.8083 - val_mean_absolute_error: 62.3065
Epoch 64/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 169us/step - loss: 52.0622 - mean_absolute_error: 52.5600 - val_loss: 61.7513 - val_mean_absolute_error: 62.2494
Epoch 65/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.1167 - mean_absolute_error: 52.6144 - val_loss: 61.6761 - val_mean_absolute_error: 62.1742
Epoch 66/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.0465 - mean_absolute_error: 52.5441 - val_loss: 61.6501 - val_mean_absolute_error: 62.1482
Epoch 67/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.2690 - mean_absolute_error: 52.7668 - val_loss: 61.5885 - val_mean_absolute_error: 62.0866
Epoch 68/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 52.1838 - mean_absolute_error: 52.6816 - val_loss: 61.5193 - val_mean_absolute_error: 62.0173
Epoch 69/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 52.2932 - mean_absolute_error: 52.7910 - val_loss: 61.4790 - val_mean_absolute_error: 61.9770
Epoch 70/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 52.2161 - mean_absolute_error: 52.7139 - val_loss: 61.4362 - val_mean_absolute_error: 61.9341
Epoch 71/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 51.8105 - mean_absolute_error: 52.3084 - val_loss: 61.3893 - val_mean_absolute_error: 61.8871
Epoch 72/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.9680 - mean_absolute_error: 52.4657 - val_loss: 61.3716 - val_mean_absolute_error: 61.8694
Epoch 73/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.9598 - mean_absolute_error: 52.4578 - val_loss: 61.3226 - val_mean_absolute_error: 61.8205
Epoch 74/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 52.0252 - mean_absolute_error: 52.5231 - val_loss: 61.2744 - val_mean_absolute_error: 61.7724
Epoch 75/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.6992 - mean_absolute_error: 52.1969 - val_loss: 61.2538 - val_mean_absolute_error: 61.7517
Epoch 76/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 171us/step - loss: 52.0519 - mean_absolute_error: 52.5500 - val_loss: 61.2099 - val_mean_absolute_error: 61.7079
Epoch 77/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.6904 - mean_absolute_error: 52.1883 - val_loss: 61.1728 - val_mean_absolute_error: 61.6708
Epoch 78/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.9257 - mean_absolute_error: 52.4238 - val_loss: 61.1264 - val_mean_absolute_error: 61.6244
Epoch 79/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.8416 - mean_absolute_error: 52.3395 - val_loss: 61.0923 - val_mean_absolute_error: 61.5903
Epoch 80/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.6937 - mean_absolute_error: 52.1915 - val_loss: 61.0770 - val_mean_absolute_error: 61.5749
Epoch 81/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.8089 - mean_absolute_error: 52.3068 - val_loss: 61.0399 - val_mean_absolute_error: 61.5379
Epoch 82/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.6829 - mean_absolute_error: 52.1808 - val_loss: 61.0072 - val_mean_absolute_error: 61.5052
Epoch 83/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.5763 - mean_absolute_error: 52.0742 - val_loss: 60.9856 - val_mean_absolute_error: 61.4835
Epoch 84/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.9467 - mean_absolute_error: 52.4444 - val_loss: 60.9594 - val_mean_absolute_error: 61.4573
Epoch 85/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.6011 - mean_absolute_error: 52.0990 - val_loss: 60.9327 - val_mean_absolute_error: 61.4307
Epoch 86/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.5068 - mean_absolute_error: 52.0045 - val_loss: 60.9066 - val_mean_absolute_error: 61.4046
Epoch 87/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.8055 - mean_absolute_error: 52.3032 - val_loss: 60.8892 - val_mean_absolute_error: 61.3872
Epoch 88/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.7151 - mean_absolute_error: 52.2127 - val_loss: 60.8535 - val_mean_absolute_error: 61.3514
Epoch 89/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.7450 - mean_absolute_error: 52.2427 - val_loss: 60.8387 - val_mean_absolute_error: 61.3366
Epoch 90/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 171us/step - loss: 51.3488 - mean_absolute_error: 51.8467 - val_loss: 60.8028 - val_mean_absolute_error: 61.3007
Epoch 91/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.6805 - mean_absolute_error: 52.1783 - val_loss: 60.8019 - val_mean_absolute_error: 61.2999
Epoch 92/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.2795 - mean_absolute_error: 51.7771 - val_loss: 60.7867 - val_mean_absolute_error: 61.2846
Epoch 93/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 51.5240 - mean_absolute_error: 52.0219 - val_loss: 60.7485 - val_mean_absolute_error: 61.2463
Epoch 94/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.4385 - mean_absolute_error: 51.9364 - val_loss: 60.7270 - val_mean_absolute_error: 61.2248
Epoch 95/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.4805 - mean_absolute_error: 51.9785 - val_loss: 60.6961 - val_mean_absolute_error: 61.1939
Epoch 96/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.2517 - mean_absolute_error: 51.7494 - val_loss: 60.6793 - val_mean_absolute_error: 61.1771
Epoch 97/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.6115 - mean_absolute_error: 52.1095 - val_loss: 60.6584 - val_mean_absolute_error: 61.1562
Epoch 98/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 51.4745 - mean_absolute_error: 51.9722 - val_loss: 60.6346 - val_mean_absolute_error: 61.1324
Epoch 99/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 51.5899 - mean_absolute_error: 52.0876 - val_loss: 60.6199 - val_mean_absolute_error: 61.1178
Epoch 100/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 51.6386 - mean_absolute_error: 52.1365 - val_loss: 60.5919 - val_mean_absolute_error: 61.0898
1671/1671 ━━━━━━━━━━━━━━━━━━━━ 0s 123us/step
Epoch 1/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 1s 181us/step - loss: 116.3773 - mean_absolute_error: 116.8763 - val_loss: 129.2792 - val_mean_absolute_error: 129.7781
Epoch 2/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 111.4610 - mean_absolute_error: 111.9594 - val_loss: 126.6263 - val_mean_absolute_error: 127.1251
Epoch 3/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 171us/step - loss: 106.6892 - mean_absolute_error: 107.1876 - val_loss: 124.2923 - val_mean_absolute_error: 124.7912
Epoch 4/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 165us/step - loss: 102.6303 - mean_absolute_error: 103.1287 - val_loss: 122.1962 - val_mean_absolute_error: 122.6954
Epoch 5/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 98.8195 - mean_absolute_error: 99.3178 - val_loss: 120.2310 - val_mean_absolute_error: 120.7298
Epoch 6/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 95.1870 - mean_absolute_error: 95.6855 - val_loss: 118.3589 - val_mean_absolute_error: 118.8578
Epoch 7/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 91.9512 - mean_absolute_error: 92.4494 - val_loss: 116.5601 - val_mean_absolute_error: 117.0590
Epoch 8/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 89.1898 - mean_absolute_error: 89.6883 - val_loss: 114.7894 - val_mean_absolute_error: 115.2881
Epoch 9/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 167us/step - loss: 85.7994 - mean_absolute_error: 86.2976 - val_loss: 113.0199 - val_mean_absolute_error: 113.5186
Epoch 10/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 83.0853 - mean_absolute_error: 83.5835 - val_loss: 111.3695 - val_mean_absolute_error: 111.8681
Epoch 11/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 166us/step - loss: 80.6460 - mean_absolute_error: 81.1443 - val_loss: 109.7526 - val_mean_absolute_error: 110.2515
Epoch 12/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 77.8684 - mean_absolute_error: 78.3666 - val_loss: 108.1845 - val_mean_absolute_error: 108.6834
Epoch 13/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 169us/step - loss: 74.9845 - mean_absolute_error: 75.4825 - val_loss: 106.6433 - val_mean_absolute_error: 107.1421
Epoch 14/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 72.8169 - mean_absolute_error: 73.3151 - val_loss: 105.1002 - val_mean_absolute_error: 105.5991
Epoch 15/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step - loss: 70.9550 - mean_absolute_error: 71.4531 - val_loss: 103.5918 - val_mean_absolute_error: 104.0907
Epoch 16/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 69.0797 - mean_absolute_error: 69.5778 - val_loss: 102.1209 - val_mean_absolute_error: 102.6198
Epoch 17/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 67.3699 - mean_absolute_error: 67.8679 - val_loss: 100.7130 - val_mean_absolute_error: 101.2117
Epoch 18/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 65.2668 - mean_absolute_error: 65.7650 - val_loss: 99.3015 - val_mean_absolute_error: 99.8001
Epoch 19/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 166us/step - loss: 63.6618 - mean_absolute_error: 64.1597 - val_loss: 97.8845 - val_mean_absolute_error: 98.3832
Epoch 20/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 166us/step - loss: 62.2458 - mean_absolute_error: 62.7438 - val_loss: 96.5210 - val_mean_absolute_error: 97.0195
Epoch 21/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 60.3816 - mean_absolute_error: 60.8795 - val_loss: 95.2053 - val_mean_absolute_error: 95.7040
Epoch 22/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 163us/step - loss: 59.4442 - mean_absolute_error: 59.9420 - val_loss: 93.8657 - val_mean_absolute_error: 94.3646
Epoch 23/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 170us/step - loss: 57.7325 - mean_absolute_error: 58.2303 - val_loss: 92.6234 - val_mean_absolute_error: 93.1222
Epoch 24/100
2673/2673 ━━━━━━━━━━━━━━━━━━━━ 0s 162us/step - loss: 57.0580 - mean_absolute_error: 57.5559 - val_loss: 91.3601 - val_mean_absolute_error: 91.8588
Epoch 25/100

RandomizedSearchCV(cv=3,
                   estimator=KerasRegressor(model=<function build_model at 0x39e20eac0>, model__input_shape=26, model__learning_rate=0.003, model__n_hidden=1, model__n_neurons=30),
                   n_iter=15,
                   param_distributions={'model__learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x32e182090>,
                                        'model__n_hidden': [0, 1, 2, 3],
                                        'model__n_neurons': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])})

O *RandomizedSearchCV* usa a validação cruzada com K-fold, e não os dados reservados para validação no parâmetro *validation_split*, que são utilizadas apenas para as funções de callbacks.

Essa exploração pode durar muito tempo. Uma vez que termine, você poderá acessar os melhores parâmetros encontratos, o melhor score e o modelo Keras treinado.

In [22]:
# encontrar os melhores hiperparâmetros
print("Melhores hiperparâmetros:", rnd_search_cv.best_params_)

# encontrar o melhor score do modelo
print("Melhor score do modelo:", rnd_search_cv.best_score_)

# obter o melhor modelo treinado
best_model = rnd_search_cv.best_estimator_.model

Melhores hiperparâmetros: {'model__learning_rate': 0.005558866265342473, 'model__n_hidden': 1, 'model__n_neurons': 38}
Melhor score do modelo: 0.6000075538953146

Agora, você pode salvar esse modelo, avaliá-lo no conjunto de testes e, se ficar satisfeito com seu desempenho, implementá-lo em produção. Usar o randomized search não é muito difícil e funciona bem para uma série de problemas. Contudo, quando o treinamento é demorado (por exemplo, para problemas mais complexos com conjuntos de dados maiores), essa abordagem explora somente uma pequena parte do espaço do hiperparâmetro. Você pode mitigar esse problema parcialmente, auxiliando no processo de pesquisa de forma manual: primeiro, execute um random search rápido usando intervalos amplos de valores de hiperparâmetros, depois rode outro random search usando intervalos menores de valores centrados nos melhores intervalos encontrados durante a primeira execução e assim por diante. Espera-se que essa abordagem foque um bom conjunto de hiperparâmetros. 

Existem outras técnicas para explorar um espaço de pesquisa com mais eficiência do que de modo aleatório. A ideia é simples: quando se comprova que uma região do espaço é boa, ela deve ser mais explorada. Essas técnicas ampliam as possibilidades e levam a soluções muito melhores em menos tempo. Existem várias bibliotecas Python para que isso que você pode utilizar.

## Conclusão

A importância desse algoritmo é tão grande que vale a pena resumir novamente: para cada instância de treinamento, o algoritmo primeiro faz uma predição (forward pass) e calcula o erro, depois passa por cada camada no sentido inverso a fim de calcular a contribuição do erro de cada conexão e, por fim, ajusta os pesos da conexão para reduzir o erro (etapa do gradiente descendente).